### ISSUE TITLE
post.date vs. post.datePublished in SitePost

### ISSUE THREAD

**Issue by zollillo** [wpioneer/gatsby-starter-lumen#13]
Hi, I'm currently exploring your nice Gatsby starter - thank you for providing this.  

In the demo, I noticed that always the current date is displayed at the end of each article instead of the date specified in the front matter (e.g. today it says _"Published 28 Sep 2016"_).

If I change `post.datePublished` to `post.date`  the correct date values are shown ([line 31 of `index.jsx`](https://github.com/wpioneer/gatsby-starter-lumen/blob/master/components/SitePost/index.jsx#L31) in `SitePost` component).

Another way to fix this could be to change the front matter variable of each post to `datePublished` (instead of `date`)  and accordingly to adjust `acces(page, 'data.datePublished')` in `SiteIndex` class.

However, I am totally new to React and it is quite possible that I am missing something...

**Comment by wpioneer** [comment]
Thank you for noticing! It looks like it should be changed to post.date.

Initially it was assumed that in the markdown can be added datePublished and dateModified for compatibility with JSON LD. ([index.md on wpioneer/blog/pages/articles/2016-06-14-cheatsheet-postgresql](https://github.com/wpioneer/blog/blob/master/pages/articles/2016-06-14-cheatsheet-postgresql/index.md), [line 33 on wpioneer/blog/components/BlogPost/index.jsx](https://github.com/wpioneer/blog/blob/master/components/BlogPost/index.jsx#L33))

**Comment by zollillo** [comment]
I just created a PR.

**Comment by wpioneer** [comment]
Excellent. Thank you
