### ISSUE TITLE
activeClassName in SiteNav component

### ISSUE THREAD

**Issue by ihororlovskyi** [wpioneer/gatsby-starter-lumen#19]
Hello, huge thanks for this gatsby theme! Very inspiring :)

What do you say if use `activeClassName` (and `onlyActiveOnIndex`) in SiteNav component from `react-router` api? 

https://github.com/ReactTraining/react-router/blob/6eeb7ad358f987520f5b519e48bdd31f725cbade/docs/API.md#link

**Comment by wpioneer** [comment]
Thank you, it merged.
