### ISSUE TITLE
How to Create a Custom Layout?

### ISSUE THREAD

**Issue by fpigeon** [wpioneer/gatsby-starter-lumen#28]
## How would I go about creating a custom layout?

For example, I want to create a `Resume` page and use a custom layout `SiteResume`.

I tried reproducing the `SitePage` component to `SiteResume` but was unable to apply it to the `Resume.md`. It kept reverting to the SitePost layout.

![gh-issue](https://cloud.githubusercontent.com/assets/4629398/23290410/1ef2b680-fa16-11e6-8ef9-a8aed013888e.png)

Thanks for this awesome starter project. Keep up the good work.

**Comment by abisz** [comment]
Hey @fpigeon,

have you taken a look into `wrappers/md.jsx`? 
There you can check the layout property and load the matching component.

I tried it, this should work:
```js
import SiteResume from '../components/SiteResume'

// ...

if (layout == 'resumee') {
    template = <SiteResume {...this.props}/>
} else if (layout != 'page') {
    template = <SitePost {...this.props}/>
} else {
    template = <SitePage {...this.props}/>
}
```

**Comment by fpigeon** [comment]
thanks @abisz. That worked for me too. I appreciate your guidance.  

I am trying to learn React in 2017 so I felt that redoing my blog using Gatsby would for me to learn it.

Thanks again!
