### ISSUE TITLE
Missing Linting

### ISSUE THREAD

**Issue by abisz** [wpioneer/gatsby-starter-lumen#29]
I noticed there are `eslint` dependencies and a lint script in `package.json`, but no configuration file, therefore it doesn't work...

Do you mind me setting it up? 
I really like the project and would love to see code style consistencies :)

**Comment by abisz** [comment]
@wpioneer do you still read this?

**Comment by wpioneer** [comment]
@abisz Hello!
Yes, it would be great if you add config. This is to the benefit of the project.

**Comment by abisz** [comment]
@wpioneer do you have preferences concerning linting rules? I'm a big fan of the [airbnb style rules](https://github.com/airbnb/javascript).

**Comment by wpioneer** [comment]
@abisz It's good ;) Gatsby also uses an airbnb config [.eslintrc#L4](https://github.com/gatsbyjs/gatsby/blob/master/.eslintrc#L4) So I think that this is the best solution for the starter.

**Comment by wpioneer** [comment]
#33
