### ISSUE TITLE
QUESTION: custom domain deployment

### ISSUE THREAD

**Issue by fpigeon** [wpioneer/gatsby-starter-lumen#30]
# What is the process for deploying blog on a custom domain?
#https://github.com/gatsbyjs/gatsby/issues/243

I was able to run the `yarn run deploy` script and push the public directory to the gh-pages branch.

Then I manually created a `CNAME`file with my custom domain.

The issue is every time I run the deploy script it removes the `CNAME` file.

Is there any way to prevent that?

<img width="1005" alt="screen shot 2017-02-25 at 12 22 35 am" src="https://cloud.githubusercontent.com/assets/4629398/23328827/965d321a-faf0-11e6-8379-0659c03b53dd.png">

**Comment by abisz** [comment]
Hey @fpigeon :)

you could move the `CNAME` file to `pages`, this way it would get automatically copied into the build folder.
Just like it's done here: https://github.com/axelclark/axelclark.com/pull/9

Hope this helps!

**Comment by fpigeon** [comment]
thanks again @abisz. Yes moving the `CNAME`file  to the `pages` directory works like a charm. This should be in the getting started guide. 

Just tested and confirmed by running `yarn run deploy` and my site was pushed and no need to add the CNAME manually.

Thanks!

**Comment by andrewsuzuki** [comment]
Better option is to put it in `/static` and it'll get copied automatically.
