### ISSUE TITLE
Autoprefixer redundancy warning

### ISSUE THREAD

**Issue by jasikpark** [wpioneer/gatsby-starter-lumen#5]
when I run `gatsby build` I get this output:

`Generating CSS
Warning: postcss-cssnext found a duplicate plugin ('autoprefixer') in your postcss plugins. This might be inefficient. You should remove 'autoprefixer' from your postcss plugin list since it's already included by postcss-cssnext.
Note: If, for a really specific reason, postcss-cssnext warnings are irrelevant for your use case, and you really know what you are doing, you can disable this warnings by setting  'warnForDuplicates' option of postcss-cssnext to 'false'.
Generating Static HTML
Compiling production bundle.js
Copying assets
Done`

**Comment by wpioneer** [comment]
I think that's okay, because the warning appears when there is overriding config CSSNext.
