### ISSUE TITLE
Static files 

### ISSUE THREAD

**Issue by GuillaumeHaben** [wpioneer/gatsby-starter-lumen#6]
Hi,

I saw that you put the "photo.jpg" in your "pages" folder. I would like to link my resume (pdf file) from the "About me" page but it doesn't work. Any idea why ?
I tried to put all my static files in the static folder but it always redirect me on the 404 page.

**Comment by wpioneer** [comment]
If an error occurs after starting `gatsby build`, is probably the reason that the files are not copied from ./pages folder to ./public.

I added a script to package.json ([package.json#L11](https://github.com/wpioneer/gatsby-starter-lumen/blob/master/package.json#L11)), which will copy the files. It can be run via npm run copy. Or, if you want to copy files directly during assembly, run in the terminal `npm run build`, instead `gatsby build`
