### ISSUE TITLE
EPEERINVALID on eslint-config-airbnb & eslint-plugin-jsx-a11y

### ISSUE THREAD

**Issue by kostasmanionis** [wpioneer/gatsby-starter-lumen#7]
Getting this :(

```
npm ERR! peerinvalid The package eslint-plugin-jsx-a11y@2.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-config-airbnb@9.0.1 wants eslint-plugin-jsx-a11y@^1.2.0
```

**Comment by wpioneer** [comment]
Try running `rm -rf node_modules/` and `npm install `. This trick should work

**Comment by kostasmanionis** [comment]
Tried it, didn't work. Not sure how should though... 

[eslint-config-airbnb@9.0.1](https://github.com/airbnb/javascript/blob/eslint-config-airbnb-v9.0.1/packages/eslint-config-airbnb/package.json#L60) is locking us in using `eslint-plugin-jsx-a11y@1.*.*`

`eslint-config-airbnb` was updated yesterday to [v10](https://github.com/airbnb/javascript/blob/eslint-config-airbnb-v10.0.0/packages/eslint-config-airbnb/package.json#L65), that accepts `eslint-plugin-jsx-a11y@2.*.*` as a peer dep. 

So I guess the solution would be just to bump `eslint-config-airbnb` to v10?

**Comment by wpioneer** [comment]
> So I guess the solution would be just to bump eslint-config-airbnb to v10?

I think this may be the right thing to do.

_Updated some dependencies._  https://github.com/wpioneer/gatsby-starter-lumen/commit/58f879350d512ed2c9545f321d1df084a95c6bb7

**Comment by kostasmanionis** [comment]
Seems to have resolved the issue, thanks! 👍 

Closing
